module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  plugins: ['stylelint-order', 'stylelint-prettier'],
  rules: {
    indentation: 2,
    'at-rule-blacklist': ['debug'],
    'at-rule-no-unknown': null,
    'at-rule-no-vendor-prefix': true,
    'block-no-empty': true,
    'block-opening-brace-space-before': 'always',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-named': 'never',
    'color-no-invalid-hex': true,
    'declaration-block-semicolon-newline-after': 'always',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    'declaration-property-value-blacklist': {
      border: ['none'],
      'border-top': ['none'],
      'border-right': ['none'],
      'border-bottom': ['none'],
      'border-left': ['none'],
    },
    'function-comma-space-after': 'always-single-line',
    'function-parentheses-space-inside': 'never-single-line',
    'function-url-quotes': 'always',
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-parentheses-space-inside': 'never',
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'no-missing-end-of-source-newline': true,
    'prettier/prettier': [
      true,
      {
        printWidth: 100,
        singleQuote: true,
        trailingComma: 'all',
      },
    ],
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': [
      'always-multi-line',
      {
        except: ['first-nested'],
        ignore: ['after-comment'],
      },
    ],
    'selector-max-compound-selectors': 3,
    'selector-max-id': 0,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-class-pattern': [
      '^[a-z0-9-_]+$',
      {
        resolveNestedSelectors: true,
        message:
          'Selector should be written in lowercase with hyphens or underscores (selector-class-pattern)',
      },
    ],
    'shorthand-property-no-redundant-values': true,
    'string-quotes': 'single',
    'order/order': [
      [
        'custom-properties',
        'declarations',
        {
          type: 'at-rule',
          name: 'media',
        },
        'rules',
      ],
    ],
    'value-no-vendor-prefix': true,
  },
};
